# Generated by Django 2.0.2 on 2018-02-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='problem',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pkey', models.CharField(max_length=100, unique=True)),
                ('pstatement', models.TextField()),
                ('pinput', models.TextField()),
                ('poutput', models.TextField()),
                ('pcode', models.TextField()),
                ('plevel', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'problem',
            },
        ),
    ]
