# Generated by Django 2.0.2 on 2018-02-23 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='problem',
            new_name='problems',
        ),
        migrations.AlterModelTable(
            name='problems',
            table='problems',
        ),
    ]
