# Generated by Django 2.0.2 on 2018-02-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20180223_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problems',
            options={'verbose_name_plural': 'problems'},
        ),
        migrations.AddField(
            model_name='problems',
            name='pname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
