# Generated by Django 2.0.2 on 2018-02-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20180223_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='pcode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
