# Generated by Django 2.0.2 on 2018-02-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20180223_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='ptag',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
