# Generated by Django 2.0.2 on 2018-03-03 07:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0006_auto_20180223_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='users_problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.problems')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user_problems',
                'db_table': 'user_problems',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
