# Generated by Django 2.0.2 on 2018-03-11 05:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_users_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='competition_problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('cpscore', models.PositiveIntegerField(default=10)),
            ],
            options={
                'verbose_name_plural': 'competition_problems',
                'db_table': 'competition_problems',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='competitions',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(blank=True, max_length=255, null=True)),
                ('cdescription', models.TextField(blank=True, null=True)),
                ('cstarttime', models.DateTimeField()),
                ('cduration', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'competitions',
                'db_table': 'competitions',
            },
        ),
        migrations.CreateModel(
            name='user_competition_problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.PositiveIntegerField()),
                ('cid', models.PositiveIntegerField()),
                ('pid', models.PositiveIntegerField()),
                ('submitted_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'user_competition_problems',
                'db_table': 'user_competition_problems',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='competition_problems',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.competitions'),
        ),
        migrations.AddField(
            model_name='competition_problems',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.problems'),
        ),
    ]
