# Generated by Django 2.0.2 on 2018-03-12 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20180311_1121'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='competition_problems',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='user_competition_problems',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user_competition_problems',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.competitions'),
        ),
        migrations.AlterField(
            model_name='user_competition_problems',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.problems'),
        ),
        migrations.AlterField(
            model_name='user_competition_problems',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
