# Generated by Django 2.0.2 on 2018-03-13 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20180312_2035'),
        ('register', '0009_auto_20180312_2234'),
    ]

    operations = [
    ]
