# Generated by Django 2.0.2 on 2018-03-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_merge_20180313_1403'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users_problem',
            managers=[
            ],
        ),
    ]
